# Generated by Django 4.2.11 on 2024-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note", name="content", field=models.TextField(null=True),
        ),
    ]
